apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: yousouf9/ticket
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: Mongo_URI
              value: 'mongodb://ticket-mongo-srv:27017/ticket'
            - name: NATS_URI
              value: 'http://nats-srv:4222'
            - name: JWT_KEY #name as it will appear in our pods
              valueFrom:
                secretKeyRef:
                  name: jwt-secret #the name of the secret key
                  key: JWT_KEY # the key of the value provided
                  optional: false #must be always present in our nodejs app
---
apiVersion: v1
kind: Service
metadata:
   name: ticket-srv
spec:
  type: ClusterIP
  selector:
    app: ticket
  ports:
    - name: ticket
      protocol: TCP
      port: 3000
      targetPort: 3000