name: auths-test
on:
 pull_request
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - env:
      JWT_KEY: ${{secrets.JWT_KEY}}
     run: cd auth && npm i && npm run test:ci
