name: test
on:
 pull_request
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Auth Test
     env:
      JWT_KEY: ${{ secrets.JWT_KEY }}
   - uses: actions/checkout@v3
   - run: cd auth && npm i && npm run test:ci
   
